### ISSUE TITLE
cannot contiune

### ISSUE THREAD

**Issue by Zeblade777** [Zeagl3/Skybax#14]
[FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for v1aK6iCHYs8=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token)
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token)
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy)
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy)
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token)
00:01:36.617 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: v1aK6iCHYs8=
00:01:36.617 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:01:36.617 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:01:36.676 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:01:38.379 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:01:38.379 [INFO] (Wabbajack.Installer.StandardInstaller) Found 45347 total files, 2587 matching filesize
00:01:38.705 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download skse64_2_00_20.7z (HTTPDownloader+State|https://skse.silverlock.org/beta/skse64_2_00_20.7z)
00:01:38.705 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

Yet I can download it put it with the downloads yet this is the only file it keeps trying to redownload. I delete it .. still tries to download.

**Comment by Zeagl3** [comment]
I uploaded a version of skse in the manual downloads channel of discord, try that one.
