### ISSUE TITLE
SKSE version is wrong

### ISSUE THREAD

**Issue by NMizuN** [Zeagl3/Skybax#15]
"00:26:45.620 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for v1aK6iCHYs8=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token)
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token)
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy)
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy)
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token)
00:26:45.914 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: v1aK6iCHYs8=
00:26:45.914 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:26:45.914 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:26:45.914 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:26:45.935 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:26:45.935 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1601 total files, 1607 matching filesize
00:26:46.403 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download skse64_2_00_20.7z (HTTPDownloader+State|https://skse.silverlock.org/beta/skse64_2_00_20.7z)
00:26:46.403 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives"

It seams I can't install the list because of the stealth update of SKSE, but I don't even know how to look for the right version since the discord server is down.

**Comment by Zeagl3** [comment]
This will be fixed when v1.5 comes out.
